; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32@^6.1.0
board = my_esp32s3
framework = arduino
monitor_speed = 115200
board_build.psram_type = qspi
board_build.arduino.psram = enabled
build_flags = 
	-DARDUINO_LOOP_STACK_SIZE=20480
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.5
	h2zero/NimBLE-Arduino@1.4.2
