[env:esp32-s3]
platform = espressif32 @ 6.13.0
board = my_esp32s3
framework = arduino
monitor_speed = 115200

board_build.arduino.psram = enabled
board_build.psram_type = qspi

lib_deps = 
    dndubins/MLX90641 @ 1.0.4
    adafruit/Adafruit BME680 Library @ 2.0.6
    adafruit/Adafruit Unified Sensor @ 1.1.14
    adafruit/Adafruit BusIO @ 1.16.1
